In [1]:
import numpy as np
import torch

In [2]:
# Use array() with nested brackets:
x = np.array([25,2,5])
x

array([25,  2,  5])

In [3]:
x_pt = torch.tensor([25, 2, 5])
x_pt

tensor([25,  2,  5])

In [4]:
y = np.array([0, 1, 2])
y

array([0, 1, 2])

In [5]:
25*0 + 2*1 + 5*2

12

In [6]:
np.dot(x, y)

12

In [7]:
y_pt = torch.tensor([0, 1, 2])
y_pt

tensor([0, 1, 2])

In [8]:
np.dot(x_pt, y_pt)

12

In [9]:
torch.dot(torch.tensor([25, 2, 5.]), torch.tensor([0, 1, 2.]))

tensor(12.)