<a href="https://colab.research.google.com/github/as4401s/Machine-Learning-Mathematics/blob/main/12_Matrix_multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

### Matrix and vector multiplication

In [13]:
A = np.array([[[3,4],[5,6],[7,8]]])
A

array([[[3, 4],
        [5, 6],
        [7, 8]]])

In [14]:
b = np.array([1,2])
b

array([1, 2])

In [15]:
np.dot(A,b)

array([[11, 17, 23]])

In [16]:
A_pt = torch.tensor([[[3,4],[5,6],[7,8]]])
A_pt

tensor([[[3, 4],
         [5, 6],
         [7, 8]]])

In [17]:
b_pt = torch.tensor([1,2])
b_pt

tensor([1, 2])

In [18]:
torch.matmul(A_pt,b_pt)

tensor([[11, 17, 23]])

### Matrix and matrix multiplication

In [19]:
A

array([[[3, 4],
        [5, 6],
        [7, 8]]])

In [20]:
B = np.array([[1,2],[9,0]])
B

array([[1, 2],
       [9, 0]])

In [21]:
np.dot(A,B)

array([[[39,  6],
        [59, 10],
        [79, 14]]])

In [22]:
A_pt

tensor([[[3, 4],
         [5, 6],
         [7, 8]]])

In [23]:
B_pt = torch.tensor([[1,2],[9,0]])
B_pt

tensor([[1, 2],
        [9, 0]])

In [24]:
torch.matmul(A_pt,B_pt)

tensor([[[39,  6],
         [59, 10],
         [79, 14]]])