<a href="https://colab.research.google.com/github/as4401s/Machine-Learning-Mathematics/blob/main/13_Matrix_Inversion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

In [7]:
X = np.array([[4,2],[-5,-3]])
X

array([[ 4,  2],
       [-5, -3]])

In [8]:
y = np.array([4,-7])
y

array([ 4, -7])

In [9]:
X_inv = np.linalg.inv(X)
X_inv

array([[ 1.5,  1. ],
       [-2.5, -2. ]])

In [10]:
w = np.dot(X_inv,y)
w

array([-1.,  4.])

### in torch

In [11]:
X_pt = torch.FloatTensor(X)
X_pt

tensor([[ 4.,  2.],
        [-5., -3.]])

In [12]:
y_pt = torch.FloatTensor(y)
y_pt

tensor([ 4., -7.])

In [14]:
w_pt = torch.inverse(X_pt).matmul(y_pt)
w_pt

tensor([-1.,  4.])