<a href="https://colab.research.google.com/github/as4401s/Machine-Learning-Mathematics/blob/main/18_Singular_Value_Decomposition_SVD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

$A = UDV^T$

Where:

* $U$ is an orthogonal $m \times m$ matrix; its columns are the **left-singular vectors** of $A$.
* $V$ is an orthogonal $n \times n$ matrix; its columns are the **right-singular vectors** of $A$.
* $D$ is a diagonal $m \times n$ matrix; elements along its diagonal are the **singular values** of $A$.

In [2]:
A = np.array([[-1,2],[3,-2],[5,7]])
A

array([[-1,  2],
       [ 3, -2],
       [ 5,  7]])

In [3]:
U,d,VT =np.linalg.svd(A)

In [4]:
U #3x3

array([[ 0.12708324,  0.47409506,  0.87125411],
       [ 0.00164602, -0.87847553,  0.47778451],
       [ 0.99189069, -0.0592843 , -0.11241989]])

In [5]:
d

array([8.66918448, 4.10429538])

In [6]:
VT

array([[ 0.55798885,  0.82984845],
       [-0.82984845,  0.55798885]])

In [7]:
np.diag(d)

array([[8.66918448, 0.        ],
       [0.        , 4.10429538]])

$D$ must have the same dimensions as $A$ for $UDV^T$ matrix multiplication to be possible:

In [9]:
D = np.concatenate((np.diag(d), [[0,0]]), axis=0)
D

array([[8.66918448, 0.        ],
       [0.        , 4.10429538],
       [0.        , 0.        ]])

In [10]:
np.dot(U, np.dot(D,VT))

array([[-1.,  2.],
       [ 3., -2.],
       [ 5.,  7.]])

In [12]:
np.dot(A,np.transpose(A))

array([[ 5, -7,  9],
       [-7, 13,  1],
       [ 9,  1, 74]])

In [13]:
np.dot(np.transpose(A),A)

array([[35, 27],
       [27, 57]])

In [15]:
np.linalg.eig(np.dot(np.transpose(A),A))

EigResult(eigenvalues=array([16.84524053, 75.15475947]), eigenvectors=array([[-0.82984845, -0.55798885],
       [ 0.55798885, -0.82984845]]))

In [16]:
np.linalg.eig(np.dot(A,np.transpose(A)))

EigResult(eigenvalues=array([7.51547595e+01, 7.08742960e-16, 1.68452405e+01]), eigenvectors=array([[-0.12708324,  0.87125411, -0.47409506],
       [-0.00164602,  0.47778451,  0.87847553],
       [-0.99189069, -0.11241989,  0.0592843 ]]))