In [1]:
import numpy as np

x = np.array([25, 2, 5]) # type argument is optional, e.g.: dtype=np.float16
x

array([25,  2,  5])

In [2]:
len(x)

3

In [3]:
x.shape

(3,)

In [4]:
type(x)

numpy.ndarray

In [5]:
x[0] # zero-indexed

25

In [6]:
type(x[0])

numpy.int64

### Vector Transposition

In [7]:
# Transposing a regular 1-D array has no effect...
x_t = x.T
x_t

array([25,  2,  5])

In [8]:
x_t.shape

(3,)

In [9]:
# ...but it does we use nested "matrix-style" brackets:
y = np.array([[25, 2, 5]])
y

array([[25,  2,  5]])

In [10]:
y.shape

(1, 3)

In [11]:
# ...but can transpose a matrix with a dimension of length 1, which is mathematically equivalent:
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [12]:
y_t.shape # this is a column vector as it has 3 rows and 1 column

(3, 1)

In [13]:
# Column vector can be transposed back to original row vector:
y_t.T

array([[25,  2,  5]])

In [14]:
y_t.T.shape

(1, 3)

### Zero Vectors

In [15]:
z = np.zeros(3)
z

array([0., 0., 0.])

### Vectors in PyTorch

In [16]:
import torch

x_pt = torch.tensor([25, 2, 5])
x_pt

tensor([25,  2,  5])