In [1]:
import numpy as np

In [2]:
x = np.array([25, 2, 5]) # type argument is optional, e.g.: dtype=np.float16
x

array([25,  2,  5])

### L2 norm

In [3]:

(25**2 + 2**2 + 5**2)**(1/2)

25.573423705088842

In [4]:
np.linalg.norm(x)

25.573423705088842

So, if units in this 3-dimensional vector space are meters, then the vector 
 has a length of 25.6m

### L1 norm

In [8]:
x

array([25,  2,  5])

In [9]:
np.abs(25) + np.abs(2) + np.abs(5)

32

### Squared L2 norm

In [5]:
x

array([25,  2,  5])

In [6]:
(25**2 + 2**2 + 5**2)

654

In [7]:
np.dot(x, x)

654

### Max norm

In [10]:
x

array([25,  2,  5])

In [11]:
np.max([np.abs(25), np.abs(2), np.abs(5)])

25

In [12]:
y= ([1,1])
y

[1, 1]

In [13]:
np.linalg.norm(y)

1.4142135623730951