In [1]:
import numpy as np

In [2]:
# Use array() with nested brackets:
X = np.array([[25, 2], [5, 26], [3, 7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [3]:
X.shape

(3, 2)

In [4]:
X.size

6

In [5]:
# Select left column of matrix X (zero-indexed)
X[:,0]

array([25,  5,  3])

In [6]:
# Select middle row of matrix X:
X[1,:]

array([ 5, 26])

In [7]:
# Another slicing-by-index example:
X[0:2, 0:2]

array([[25,  2],
       [ 5, 26]])

### Matrices in PyTorch

In [10]:
import torch

X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [11]:
X_pt.shape

torch.Size([3, 2])

In [12]:
X_pt[1,:]

tensor([ 5, 26])