In [1]:
import numpy as np

In [2]:
# Use array() with nested brackets:
X = np.array([[25, 2], [5, 26], [3, 7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [3]:
X.T

array([[25,  5,  3],
       [ 2, 26,  7]])

### Pytorch

In [4]:
import torch

X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [5]:
X_pt.T

tensor([[25,  5,  3],
        [ 2, 26,  7]])