In [1]:
import numpy as np

In [2]:
# Use array() with nested brackets:
X = np.array([[25, 2], [5, 26], [3, 7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [3]:
X*2

array([[50,  4],
       [10, 52],
       [ 6, 14]])

In [4]:
X*2+2

array([[52,  6],
       [12, 54],
       [ 8, 16]])

### Pytorch

In [5]:
import torch

X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [6]:

X_pt*2+2 # Python operators are overloaded; could alternatively use torch.mul() or torch.add()

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [7]:
torch.add(torch.mul(X_pt, 2), 2)

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

If two tensors have the same size, operations are often by default applied element-wise. This is not matrix multiplication, which we'll cover later, but is rather called the Hadamard product or simply the element-wise product.

In [8]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [9]:
A = X+2

In [10]:
A+X

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [11]:
A*X

array([[675,   8],
       [ 35, 728],
       [ 15,  63]])

In [12]:
A_pt = X_pt + 2

In [13]:
A_pt + X_pt

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [14]:
A_pt * X_pt

tensor([[675,   8],
        [ 35, 728],
        [ 15,  63]])