In [1]:
import numpy as np
import torch

In [2]:
# Use array() with nested brackets:
X = np.array([[25, 2], [5, 26], [3, 7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [3]:
X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [4]:
X.sum()

68

In [5]:
torch.sum(X_pt)

tensor(68)

In [6]:
# Can also be done along one specific axis alone, e.g.:
X.sum(axis=0) # summing over all rows

array([33, 35])

In [7]:
torch.sum(X_pt)

tensor(68)

In [8]:
# Can also be done along one specific axis alone, e.g.:
X.sum(axis=0) # summing over all rows

array([33, 35])

In [9]:
X.sum(axis=1) # summing over all columns

array([27, 31, 10])

In [10]:
torch.sum(X_pt, 0)

tensor([33, 35])

In [11]:
torch.sum(X_pt, 1)

tensor([27, 31, 10])

Many other operations can be applied with reduction along all or a selection of axes, e.g.:

maximum
minimum
mean
product